### ISSUE TITLE
TypeError on Server

### ISSUE THREAD

**Issue by ellieLitwack** [developmentseed/sentinel-util#2]
Runs fine on desktop, but when on server, downloads all products then gives this error:
```
Traceback (most recent call last):
  File "sentinel-util.py", line 183, in <module>
    main()
  File "sentinel-util.py", line 110, in main
    warp(file, dir)
  File "sentinel-util.py", line 175, in warp
    gdal.Warp(tempfile, file, dstSRS='EPSG:3857')
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/osgeo/gdal.py", line 549, in Warp
    return wrapper_GDALWarpDestName(destNameOrDestDS, srcDSTab, opts, callback, callback_data)
TypeError: in method 'wrapper_GDALWarpDestName', argument 4 of type 'GDALWarpAppOptions *'
```
The files are downloaded and unzipped but aren't warped or switched from 16-bit to byte.

**Comment by eliLitwack** [comment]
Solved - the issue was that gdalwarp was being passed a gdal image object (from ```file = gdal.open(filename)``` instead of a string as the output directory

**Comment by ellieLitwack** [comment]
The GDAL_DATA env var is not set - a system issue, not a code issue
